apiVersion: v1
kind: Service
metadata:
  name: lacework-shift-left-demo
  labels:
    app: lacework-shift-left-demo
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    app: lacework-shift-left-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lacework-shift-left-demo
  labels:
    app: lacework-shift-left-demo
spec:
  selector:
    matchLabels:
      app: lacework-shift-left-demo
  replicas: 3
  template:
    metadata:
      labels:
        app: lacework-shift-left-demo
    spec:
      containers:
        - name: lacework-shift-left-demo
          image: ghcr.io/timarenz/lacework-shift-left-demo:v0.0.2
          ports:
            - containerPort: 5000
