name: release-application
on:
  push:
    tags:
      - "v*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  push_to_registry:
    name: Release application
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Scan for vulnerabilities
        uses: timarenz/lw-scanner-action@v0.3.0
        env:
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
          LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
          LW_SCANNER_SAVE_RESULTS: true
          LW_SCANNER_SCAN_LIBRARY_PACKAGES: true
          LW_SCANNER_DISABLE_UPDATES: true
        with:
          image_name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          image_tag: ${{ steps.meta.outputs.version }}
          fail_only_if_vulnerabilities_fixable: true
          fail_if_critical_vulnerabilities_found: false
          fail_if_high_vulnerabilities_found: false
          fail_if_medium_vulnerabilities_found: false
          fail_if_low_vulnerabilities_found: false
          fail_if_info_vulnerabilities_found: false
          save_html_report: true
          html_report_file_name: lacework.html

      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: lacework-shift-left-k8s
          location: europe-west4
          credentials: ${{ secrets.GCP_CREDENTIALS }}

      - name: Update Kubernetes deployment
        run: kubectl set image deployment/lacework-shift-left-demo lacework-shift-left-demo=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}

      - name: Check rollout status
        run: kubectl rollout status deployment/lacework-shift-left-demo -w
